// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkZCBo2a_91N8JilFlB4EUqjbnCa7V-GY',
    appId: '1:463909623237:web:6b1d92bbb2ea67f82e27ac',
    messagingSenderId: '463909623237',
    projectId: 'newsrmessages',
    authDomain: 'newsrmessages.firebaseapp.com',
    storageBucket: 'newsrmessages.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC__3IQA05coQf32jbMJ9VnfnxzWDDQSIY',
    appId: '1:463909623237:android:0845b3f6490313c82e27ac',
    messagingSenderId: '463909623237',
    projectId: 'newsrmessages',
    storageBucket: 'newsrmessages.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAM9IFF_85yj6pI_IASWL_-Tau93eKqM4Q',
    appId: '1:463909623237:ios:67638e4d5edc50222e27ac',
    messagingSenderId: '463909623237',
    projectId: 'newsrmessages',
    storageBucket: 'newsrmessages.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAM9IFF_85yj6pI_IASWL_-Tau93eKqM4Q',
    appId: '1:463909623237:ios:67638e4d5edc50222e27ac',
    messagingSenderId: '463909623237',
    projectId: 'newsrmessages',
    storageBucket: 'newsrmessages.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkZCBo2a_91N8JilFlB4EUqjbnCa7V-GY',
    appId: '1:463909623237:web:8dbea60aba42b89f2e27ac',
    messagingSenderId: '463909623237',
    projectId: 'newsrmessages',
    authDomain: 'newsrmessages.firebaseapp.com',
    storageBucket: 'newsrmessages.firebasestorage.app',
  );
}
